"""add document file hash

Revision ID: edd94f92c671
Revises: d9dd1bdee535
Create Date: 2026-09-04 15:49:11.812844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd94f92c671'
down_revision: Union[str, Sequence[str], None] = 'd9dd1bdee535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_unique_constraint('uq_documents_user_file_hash', 'documents', ['user_id', 'file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_user_file_hash', 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
